# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
project_name: autodelete
before:
  hooks:
    - rm -rf build
    - git clone https://github.com/riking/AutoDelete.git build
builds:
  - dir: build
    main: ./cmd/autodelete
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    hooks:
      post:
        - sh -c "upx --best --lzma \"{{ .Path }}\" || /bin/true"
    goos:
      - linux
      - windows
      - darwin
    flags:
      - "-tags=netgo,osusergo,static_build"
      - "-installsuffix=netgo"
      - "-trimpath"
    ldflags:
      - "-s"
      - "-w"
      - "-X main.version={{.Version}}"
      - "-X main.commit={{.Commit}}"
      - "-X main.date={{.CommitDate}}"
      - "-X main.builtBy=github-actions"
      - "-extldflags=-static"
    targets:
      - linux_amd64
      - linux_arm64
      - linux_arm_6
      - freebsd_amd64
      - windows_amd64
      - darwin_amd64
archives:
  - id: archives
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
  - id: binary
    format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
release:
  draft: false
  prerelease: auto
  mode: replace
  disable: false
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  skip: true
