# see config.go "type Config" for more fields
clientid:
clientsecret:
bottoken:
adminuser:
http:
  listen: "localhost:2202"
  public: "https://home.riking.org"
backlog_limit: 200
errorlog: ""
statusmessage: "in the garbage"
