name: release

on:
  push:
    branches: [master, main]
    tags: [v*]
    paths-ignore: [".gitignore", "**/*.md", ".github/ISSUE_TEMPLATE/**"]

jobs:
  docker-release:
    uses: lrstanley/.github/.github/workflows/docker-release.yml@master
    secrets: inherit
    with:
      dockerfile: Dockerfile
