name: release

on:
  pull_request:
    branches: [master, main]
    paths-ignore: [".gitignore", "**/*.md", ".github/ISSUE_TEMPLATE/**"]
    types: [opened, edited, reopened, synchronize, unlocked]
  push:
    branches: [master, main]
    tags: [v*]
    paths-ignore: [".gitignore", "**/*.md", ".github/ISSUE_TEMPLATE/**"]

jobs:
  docker-release:
    needs: [go-test, go-lint]
    uses: lrstanley/.github/.github/workflows/docker-release.yml@master
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
